
babel = Builder(action = 'babel -h $SOURCE -o mopin -xf keys.cosmo $TARGET',
                     suffix = '.mop', single_source=True)

mopac = Builder(action = 'mopac $SOURCE', suffix = '.cos', single_source=True)

env = Environment(BUILDERS = {'Babel' : babel})
env.Append(BUILDERS = {'Mopac' : mopac})

mops = env.Babel(Glob('*.mol'))
env.Depends(mops, 'keys.cosmo')

env.Mopac(mops)


