
# www.scons.org scritp files for COSMO computations using both MOPAC and GAMESS

import os
env = Environment()

env['ENV']['USER'] = os.environ['USER']
env['ENV']['HOME'] = os.environ['HOME']

# Mopac stuff
babelmop = Builder(action = 'babel -h $SOURCE -o mopin -xf keys.cosmo $TARGET',
                     suffix = '.mop', single_source=True)
mopac = Builder(action = 'mopac $SOURCE', suffix = '.cos', single_source=True)
env.Append(BUILDERS = {'BabelMop' : babelmop})
env.Append(BUILDERS = {'Mopac' : mopac})

# Gamess stuff
babelgam = Builder(action = 'babel -h $SOURCE -o gamin -xf keys.gamess $TARGET',
                     suffix = '.inp', single_source=True)
# Gamess also produces a .dat file
def gamess_targets(target, source, env):
           target.append('$HOME/src/gamess07/$TARGET.dat')
           return target, source
gamess = Builder(action = os.environ['HOME'] + '/src/gamess07/rungms $SOURCE > $TARGET', suffix = '.gout',
	single_source=True) # , emitter = gamess_targets)
env.Append(BUILDERS = {'BabelGam' : babelgam})
env.Append(BUILDERS = {'Gamess' : gamess})

# Build all files for Mopac
mops = env.BabelMop(Glob('*.mol'))
env.Depends(mops, 'keys.cosmo')
mopacBuild = env.Mopac(mops)
env.Alias('mopac', mopacBuild)
env.Default('mopac')

# Build all files for Gamess
# Delete all DAT files, otherwise gamess will stop
delAction = Delete(Glob(os.environ['HOME'] + '/src/gamess07/tmp/*.dat'))
Execute(delAction)
# Convert mol files to gamess input
inps = env.BabelGam(Glob('*.mol'))
env.Depends(inps, 'keys.gamess')
# env.Depends(inps, delAction)
# process files with gamess
gamessBuild = env.Gamess(inps)
Alias('gamess', gamessBuild)


